### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by Veradictus** [DanielRuf/esdoc-next#1]
Not sure how far you've come with this yet, but I appreciate your efforts :)

```esdoc/out/src/ESDoc.js:307
            throw _iteratorError3;
            ^

TypeError: Cannot read property 'line' of undefined
    at InvalidCodeLogger.showFile (/Users/flavius/Projects/Kaetram-Open/node_modules/esdoc/out/src/Util/InvalidCodeLogger.js:93:38)
    at Function._getFactory (/Users/flavius/Projects/Kaetram-Open/node_modules/esdoc/out/src/ESDoc.js:336:39)
    at Function._traverse (/Users/flavius/Projects/Kaetram-Open/node_modules/esdoc/out/src/ESDoc.js:367:36)
    at /Users/flavius/Projects/Kaetram-Open/node_modules/esdoc/out/src/ESDoc.js:180:26
    at Function._walk (/Users/flavius/Projects/Kaetram-Open/node_modules/esdoc/out/src/ESDoc.js:292:13)
    at Function._walk (/Users/flavius/Projects/Kaetram-Open/node_modules/esdoc/out/src/ESDoc.js:294:18)
    at Function._walk (/Users/flavius/Projects/Kaetram-Open/node_modules/esdoc/out/src/ESDoc.js:294:18)
    at Function.generate (/Users/flavius/Projects/Kaetram-Open/node_modules/esdoc/out/src/ESDoc.js:119:12)
    at ESDocCLI.exec (/Users/flavius/Projects/Kaetram-Open/node_modules/esdoc/out/src/ESDocCLI.js:78:27)
    at Object.<anonymous> (/Users/flavius/Projects/Kaetram-Open/node_modules/esdoc/out/src/ESDocCLI.js:214:7)```

**Comment by DanielRuf** [comment]
Hi @Veradictus,

please provide the steps that you have done so I can reproduce this.

**Comment by Veradictus** [comment]
Oh I did a sketch implementation of this.

1) Install original esdoc w/ `npm install esdoc`
2) Compile this code and transfer over dependencies
3) Attempt to run

If you could guide me through how to run this, that'd be awesome!

**Comment by DanielRuf** [comment]
Generally https://github.com/DanielRuf/esdoc-next/blob/master/src/Util/InvalidCodeLogger.js#L18 never defines `error`.

**Comment by DanielRuf** [comment]
I will have to check that then.

**Comment by DanielRuf** [comment]
You can test that locally by running `npm build` or `yarn build` and then execute `out/src/ESDocCLI.js`.

See the `bin` setting in the package.json file:
```
"bin": {
    "esdoc": "out/src/ESDocCLI.js"
  }
```

**Comment by DanielRuf** [comment]
You can test that locally by running `npm build` or `yarn build` and then execute `src/ESDocCLI.js` in `out`.

See the `bin` setting in the package.json file:
```
"bin": {
    "esdoc": "out/src/ESDocCLI.js"
  }
```

**Comment by DanielRuf** [comment]
> InvalidCodeLogger.showFile (esdoc/out/src/Util/InvalidCodeLogger.js:93:38)

Can you add a `console.log(e)` there? This should show the actual error. At first sight this is caused by incompatibilities with the lint plugin and Babel 7 and some problematic code parts.

**Comment by DanielRuf** [comment]
I had to change a few things to get it working.

https://github.com/DanielRuf/esdoc-next/commit/4486b30afa543ca16a85c900bc6f38761302d8ec and two patches for two plugins.

[esdoc-type-inference-plugin+1.0.2.patch.txt](https://github.com/DanielRuf/esdoc-next/files/3868984/esdoc-type-inference-plugin%2B1.0.2.patch.txt)
[esdoc-lint-plugin+1.0.2.patch.txt](https://github.com/DanielRuf/esdoc-next/files/3868985/esdoc-lint-plugin%2B1.0.2.patch.txt)

**Comment by DanielRuf** [comment]
I had to change a few things to get it working.

https://github.com/DanielRuf/esdoc-next/commit/4486b30afa543ca16a85c900bc6f38761302d8ec and two patches for two plugins:

[esdoc-type-inference-plugin+1.0.2.patch.txt](https://github.com/DanielRuf/esdoc-next/files/3868984/esdoc-type-inference-plugin%2B1.0.2.patch.txt)
[esdoc-lint-plugin+1.0.2.patch.txt](https://github.com/DanielRuf/esdoc-next/files/3868985/esdoc-lint-plugin%2B1.0.2.patch.txt)
